spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/compasso
    url: jdbc:h2:mem:compasso
    username: sa
    password: 
    driverClassName: org.h2.Driver
    platform: h2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  
    
server:
  port : 9999
